import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weights: ["400", "500", "600", "700"], 
});

export const metadata = {
  title: "MAH Marriage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-green-800`}>
        {children}
      </body>
    </html>
  );
}
